# encoding: utf-8
# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://vigo.github.com/git-tips
title: Octopress Türkçe Blog
subtitle: "Hacker'lar için blog yapma sistemi."
author: 'Ad, Soyad'
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day


# Türkçe'de ordinal olmadığı için default olarak
# Aralık 26 Pazartesi, 2011 yaptım
# %B %e %A, %Y
date_format: "ordinal"
# date_format: "%d %B %A, %Y, %k:%M" # 25 Aralık Pazar, 2011, 11:53

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: atom.xml # do not put /
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/kategoriler
category_title_prefix: 'Kategori: '

tag_dir: blog/etiket
tag_title_prefix: 'Etiket: '

markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
# excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_link: "Devamı &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: false       # Converts page and post titles to tilecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [
    custom/asides/hakkimda.html,
    asides/recent_posts.html,
    asides/tag_cloud.html,
    asides/categories.html,
    asides/github.html,
    asides/twitter.html,
    asides/delicious.html,
    asides/pinboard.html,
    asides/googleplus.html
]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: 
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: 
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: true
facebook_locale: tr_TR # en_US

# Attach Instapaper link for posts
instapaper: true
instapaper_button_title: "Instapaper"
instapaper_link_title: "Instapaper'e gönder..."

# Open links in New window or Tab
open_links_in_new_window: true


# Vimeo
# Available variables are:
#   %{id}
#   %{title}
#   %{author_url}
#   %{author_name}
#   %{duration}
#   %{description}
#   %{thumbnail_url}
# Example:
# '<p><a href="http://vimeo.com/%{id}">%{title}</a> from <a href="%{author_url}">%{author_name}</a> on <a href="http://vimeo.com/">Vimeo</a>.</p>'
vimeo_information_format: '<p><a href="http://vimeo.com/%{id}">%{title}</a> / <a href="%{author_url}">%{author_name}</a></p>'

tag_cloud_size: 30
tag_cloud_max_ranks: 15